stages:
  - test
  - securityScan
  - publish
  - publish-semver
  - promote-dev
  - release

include:
  - project: audacy-inc/audacy/pipeline-templates
    ref: pipeline-templates-0.2.5
    file:
      - gitlab-ci/kaniko_gitlab-ci.yml
      - gitlab-ci/security-scans_gitlab-ci.yml
  - local: .pe-reports.gitlab-ci.yml
  - local: darkstar/.gitlab-ci.yml
